from django.db import models
from django.contrib.auth.models import User


class DashboardStats(models.Model):
    games_played = models.IntegerField()
    wins = models.IntegerField()
    losses = models.IntegerField()
    total_goals = models.IntegerField()
    total_saves = models.IntegerField()
    total_assists = models.IntegerField()
    total_clean_sheets = models.IntegerField()
    total_yellow_cards = models.IntegerField()
    total_red_cards = models.IntegerField()
    total_blue_cards = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
class Player(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    assists = models.IntegerField()
    yellow_cards = models.IntegerField()
    red_cards = models.IntegerField()
    goals = models.IntegerField()
    shutouts = models.IntegerField()
    saves = models.IntegerField()
class StatsPerGame(models.Model):
    vs = models.CharField(max_length=100, blank=True, null=True)
    goals = models.IntegerField(blank=True, null=True)
    assists = models.IntegerField(blank=True, null=True)
    completed_passes = models.IntegerField(blank=True, null=True)
    total_passes = models.IntegerField(blank=True, null=True)
    turnovers = models.IntegerField(blank=True, null=True)
    saves = models.IntegerField(blank=True, null=True)
    clean_sheets = models.IntegerField(blank=True, null=True)
    issued_card = models.IntegerField(blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    wl = models.BooleanField(default=True, blank=True)
    assister = models.ForeignKey('Player', on_delete=models.SET_NULL, related_name='assists_provided', null=True, blank=True)
    goalscorer = models.ForeignKey('Player', on_delete=models.SET_NULL, related_name='goals_scored', null=True, blank=True)
    cardgiven = models.ForeignKey('Player', on_delete=models.SET_NULL, related_name='cards_given', null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)