# Generated by Django 4.2.6 on 2023-10-27 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('assists', models.IntegerField()),
                ('yellow_cards', models.IntegerField()),
                ('red_cards', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('shutouts', models.IntegerField()),
                ('saves', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StatsPerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vs', models.CharField(max_length=100)),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('completed_passes', models.IntegerField()),
                ('total_passes', models.IntegerField()),
                ('turnovers', models.IntegerField()),
                ('saves', models.IntegerField()),
                ('clean_sheets', models.IntegerField()),
                ('issued_card', models.IntegerField()),
                ('date', models.DateField()),
                ('wl', models.BooleanField(default=True)),
                ('assister', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assists_provided', to='application.player')),
                ('cardgiven', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_given', to='application.player')),
                ('goalscorer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals_scored', to='application.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('total_goals', models.IntegerField()),
                ('total_saves', models.IntegerField()),
                ('total_assists', models.IntegerField()),
                ('total_clean_sheets', models.IntegerField()),
                ('total_yellow_cards', models.IntegerField()),
                ('total_red_cards', models.IntegerField()),
                ('total_blue_cards', models.IntegerField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
