# Generated by Django 4.1.12 on 2023-10-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statspergame',
            name='assists',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statspergame',
            name='clean_sheets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statspergame',
            name='completed_passes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statspergame',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statspergame',
            name='goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statspergame',
            name='issued_card',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statspergame',
            name='saves',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statspergame',
            name='total_passes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statspergame',
            name='turnovers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statspergame',
            name='vs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='statspergame',
            name='wl',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
