# Generated by Django 4.1.12 on 2023-10-31 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_statspergame_assists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='player',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='player',
            name='red_cards',
        ),
        migrations.RemoveField(
            model_name='player',
            name='saves',
        ),
        migrations.RemoveField(
            model_name='player',
            name='shutouts',
        ),
        migrations.RemoveField(
            model_name='player',
            name='yellow_cards',
        ),
        migrations.RemoveField(
            model_name='statspergame',
            name='issued_card',
        ),
        migrations.AddField(
            model_name='statspergame',
            name='red_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red_cards', to='application.player'),
        ),
        migrations.AddField(
            model_name='statspergame',
            name='savers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saves_games', to='application.player'),
        ),
        migrations.AddField(
            model_name='statspergame',
            name='shutouts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shutouts_games', to='application.player'),
        ),
        migrations.AddField(
            model_name='statspergame',
            name='yellow_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yellow_cards', to='application.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='statspergame',
            name='assister',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_games', to='application.player'),
        ),
        migrations.AlterField(
            model_name='statspergame',
            name='cardgiven',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_given_games', to='application.player'),
        ),
        migrations.AlterField(
            model_name='statspergame',
            name='goalscorer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scored_games', to='application.player'),
        ),
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('completed_passes', models.IntegerField(default=0)),
                ('total_passes', models.IntegerField(default=0)),
                ('turnovers', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('clean_sheets', models.IntegerField(default=0)),
                ('issued_card', models.CharField(blank=True, max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.statspergame')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.player')),
            ],
        ),
        migrations.AddField(
            model_name='statspergame',
            name='players',
            field=models.ManyToManyField(through='application.PlayerGameStats', to='application.player'),
        ),
    ]
