# Generated by Django 4.2.3 on 2023-11-07 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0004_remove_dashboardstats_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergamestats',
            name='issued_card',
        ),
        migrations.RemoveField(
            model_name='statspergame',
            name='players',
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='red_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='yellow_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
